name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - sphinx==4.0.2
  - pip:
    - sphinxcontrib-matlabdomain==0.12.0
    - sphinx-rtd-theme==1.0.0
    - sphinx-design==0.0.12